### ISSUE TITLE
Pseudocode question 

### ISSUE THREAD

**Issue by Evgeniy-02** [JonathanRadotski/multinomial_naivebayes#2]
Could you tell me if there is a mistake here? 
```
##    for word in test data:
        check if word exist in word dict spam (yes = prob spam word[word] | else = prob spam word [word])
        check if word exist in word dict not spam (yes = prob not spam word[word] | else = prob not spam word [word])
```

**Comment by JonathanRadotski** [comment]
Nice catch @Evgeniy-02! The algorithm should look first if the test word exists in `dict_prob_spam` and if not it will check if it exists in `dict_prob_not_spam`, after that then it will calculate and `append` to **both** `probability_spam` and `probability_not_spam`.

**Comment by Evgeniy-02** [comment]
Thank you, but it's not clear to me yet

`        if word doesn't exist in both category then prob not spam word[word] and prob spam word[word]`

**Comment by JonathanRadotski** [comment]
I'm sorry this is my bad. I think it safe to say that we should  append `1` instead of `undefined` value caused by `prob not spam word[word]` and `prob spam word[word]` not in the dictionary. Since the value for `spam_meter` and `not_spam_meter` is multiplied by the value inside probability_spam. This project have many loop-holes if i recall.

Because this project is about 3/4 years ago. I think this project is past due and will not be maintained anymore. Anyway, thanks for your time and great feedback @Evgeniy-02 ! 💯
